# version: '3.9'
services:
  todoapp:
    build: .
    container_name: php_todo_app
    ports:
      - "8089:8000"
    networks:
      - my_network
    volumes:
      - todo_app:/var/www
    environment:
      DB_HOST: mysql-server
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: celyne
      DB_PASSWORD: PassWord.1
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: php_todo_db
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: celyne
      MYSQL_PASSWORD: PassWord.1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql
      - ./create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  my_network:

volumes:
  todo_app:
  db_data: